import React, { useState, useEffect } from 'react';
import axios from 'axios';
import { Link } from 'react-router-dom';
import {
  TrendingUp, AlertTriangle, Building2, BarChart3, ArrowRight,
  CheckCircle, XCircle, AlertCircle, Activity, Zap, DollarSign,
  Users, Target, TrendingDown, Sparkles, Brain, ChevronRight
} from 'lucide-react';
import {
  CircularProgress,
  ExecutiveKPICard,
  InsightCard,
  StatusBadge,
  MiniSparkline
} from '../components/ExecutiveComponents';

interface Metric {
  name: string;
  value: string;
  status?: string;
}

interface Department {
  id: string;
  name: string;
  icon: string;
  theme: string;
  healthScore: number;
  keyMetrics: Metric[];
  url: string;
}

interface ExecutiveSummary {
  overallHealth: number;
  overallHealthStatus: string;
  departmentsMonitored: number;
  totalKPIs: number;
  criticalAlerts: number;
  warningAlerts: number;
  period: {
    label: string;
    startDate: string;
    endDate: string;
  };
}

interface ExecutiveKPI {
  name: string;
  value: string;
  status?: string;
  change: string;
}

interface ExecutiveKPICategory {
  category: string;
  kpis: ExecutiveKPI[];
}

interface DashboardData {
  success: boolean;
  executiveSummary: ExecutiveSummary;
  departments: Department[];
  topExecutiveKPIs: ExecutiveKPICategory[];
  generatedAt: string;
}

const DashboardExecutive: React.FC = () => {
  const [data, setData] = useState<DashboardData | null>(null);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);

  useEffect(() => {
    const fetchData = async () => {
      try {
        setLoading(true);
        const response = await axios.get('/api/executive/dashboard');
        setData(response.data);
        setError(null);
      } catch (err) {
        console.error('Error fetching Executive Dashboard data:', err);
        setError('Failed to load Executive Dashboard. Please ensure the backend is running.');
      } finally {
        setLoading(false);
      }
    };

    fetchData();
  }, []);

  const getHealthColor = (score: number) => {
    if (score >= 80) return 'text-green-400 border-green-500 bg-green-500/10';
    if (score >= 65) return 'text-blue-400 border-blue-500 bg-blue-500/10';
    if (score >= 50) return 'text-yellow-400 border-yellow-500 bg-yellow-500/10';
    return 'text-red-400 border-red-500 bg-red-500/10';
  };

  const getStatusColor = (status?: string) => {
    if (!status) return 'text-gray-400';
    switch (status.toLowerCase()) {
      case 'excellent':
      case 'good':
        return 'text-green-400';
      case 'warning':
        return 'text-yellow-400';
      case 'critical':
        return 'text-red-400';
      default:
        return 'text-gray-400';
    }
  };

  const getThemeColor = (theme: string) => {
    const colors: { [key: string]: string } = {
      cyan: 'from-cyan-500 to-blue-600',
      orange: 'from-orange-500 to-red-600',
      blue: 'from-blue-500 to-indigo-600',
      purple: 'from-purple-500 to-pink-600',
      teal: 'from-teal-500 to-cyan-600',
      green: 'from-green-500 to-emerald-600',
      amber: 'from-amber-500 to-orange-600',
    };
    return colors[theme] || 'from-gray-500 to-gray-600';
  };

  if (loading) {
    return (
      <div className="flex items-center justify-center min-h-screen bg-gray-900">
        <div className="text-center">
          <div className="animate-spin rounded-full h-16 w-16 border-b-2 border-purple-500 mx-auto mb-4"></div>
          <p className="text-gray-400 text-lg">Loading Executive Dashboard...</p>
        </div>
      </div>
    );
  }

  if (error || !data) {
    return (
      <div className="flex items-center justify-center min-h-screen bg-gray-900">
        <div className="text-center max-w-md">
          <AlertCircle className="mx-auto mb-4 text-red-500" size={64} />
          <p className="text-red-400 mb-2 text-xl">Error Loading Dashboard</p>
          <p className="text-gray-400">{error}</p>
        </div>
      </div>
    );
  }

  const { executiveSummary, departments = [], topExecutiveKPIs = [] } = data;

  // Generate sample sparkline data for KPIs (in production, this would come from API)
  const generateSparklineData = () => {
    return Array.from({ length: 7 }, () => Math.floor(Math.random() * 30) + 70);
  };

  // Mock AI insights (in production, these would be generated by AI backend)
  const aiInsights = [
    {
      type: 'opportunity' as const,
      title: 'Revenue Growth Opportunity Identified',
      description: 'Customer Success metrics show 94% satisfaction. Cross-selling initiatives could increase revenue by 15-20% this quarter.',
      priority: 'high' as const,
      impact: '+$2.4M potential revenue',
      actionLabel: 'View Strategy'
    },
    {
      type: 'risk' as const,
      title: 'Supply Chain Bottleneck Detected',
      description: 'Inventory turnover has slowed by 12%. Alternative suppliers recommended to maintain production targets.',
      priority: 'high' as const,
      impact: 'Potential 8% cost increase',
      actionLabel: 'Review Options'
    },
    {
      type: 'achievement' as const,
      title: 'Safety Performance Milestone',
      description: 'HSE department achieved 180 days without incidents, 40% better than industry average.',
      priority: 'medium' as const,
      impact: '$450K cost avoidance',
      actionLabel: 'View Details'
    }
  ];

  return (
    <div className="min-h-screen bg-gradient-to-br from-gray-900 via-purple-900/30 to-gray-900 p-4 md:p-8">
      <div className="max-w-[2000px] mx-auto">
        {/* Premium Header with Quick Stats */}
        <div className="mb-8 animate-fade-in-up">
          <div className="flex items-start justify-between mb-6">
            <div>
              <div className="flex items-center gap-3 mb-3">
                <div className="p-3 bg-gradient-to-br from-purple-500/20 to-pink-500/20 rounded-2xl border border-purple-500/30">
                  <Sparkles className="text-purple-400" size={32} />
                </div>
                <div>
                  <h1 className="text-5xl font-bold bg-gradient-to-r from-purple-400 via-pink-500 to-purple-600 bg-clip-text text-transparent">
                    Executive Command Center
                  </h1>
                  <p className="text-gray-400 text-lg mt-1">
                    Real-time intelligence for strategic decision-making
                  </p>
                </div>
              </div>
              <div className="flex items-center gap-4 text-sm">
                <span className="text-gray-500">
                  📅 {executiveSummary?.period?.startDate || 'N/A'} → {executiveSummary?.period?.endDate || 'N/A'}
                </span>
                <span className="text-gray-600">•</span>
                <span className="text-gray-500">
                  🔄 Updated {new Date(data.generatedAt).toLocaleTimeString()}
                </span>
                <span className="text-gray-600">•</span>
                <StatusBadge status={executiveSummary?.overallHealthStatus === 'Excellent' ? 'excellent' : 'good'} label={executiveSummary?.overallHealthStatus} />
              </div>
            </div>
          </div>
        </div>

        {/* Hero Metrics - Circular Progress Rings */}
        <div className="grid grid-cols-1 lg:grid-cols-4 gap-6 mb-8">
          {/* Company Health Score - Main Hero Metric */}
          <div className="lg:col-span-1 bg-gradient-to-br from-gray-800/80 via-gray-900/80 to-gray-800/80 border-2 border-purple-500/30 rounded-2xl p-8 flex flex-col items-center justify-center hover:border-purple-500/60 transition-all duration-300 animate-scale-in backdrop-blur-sm">
            <CircularProgress
              value={executiveSummary?.overallHealth || 0}
              status={executiveSummary?.overallHealth >= 80 ? 'excellent' : executiveSummary?.overallHealth >= 65 ? 'good' : executiveSummary?.overallHealth >= 50 ? 'warning' : 'critical'}
              size={140}
              strokeWidth={12}
              showLabel={false}
            />
            <h3 className="text-white font-bold text-lg mt-6 text-center">Company Health Score</h3>
            <p className="text-gray-400 text-sm text-center mt-1">{executiveSummary?.overallHealthStatus}</p>
            <div className="mt-4 flex items-center gap-2 text-green-400 text-sm">
              <TrendingUp size={16} />
              <span className="font-semibold">+5% vs last period</span>
            </div>
          </div>

          {/* Quick Stats Grid */}
          <div className="lg:col-span-3 grid grid-cols-1 md:grid-cols-3 gap-6">
            {/* Departments */}
            <div className="bg-gradient-to-br from-blue-500/10 via-cyan-500/5 to-blue-500/10 border-2 border-blue-500/30 rounded-xl p-6 hover:border-blue-500/60 transition-all duration-300 backdrop-blur-sm group">
              <div className="flex items-start justify-between mb-4">
                <div className="p-3 bg-blue-500/20 rounded-xl group-hover:scale-110 transition-transform duration-300">
                  <Building2 className="text-blue-400" size={28} />
                </div>
                <div className="text-right">
                  <p className="text-5xl font-bold text-white mb-1">{executiveSummary?.departmentsMonitored || 0}</p>
                  <p className="text-xs text-blue-400 font-semibold uppercase tracking-wide">Departments</p>
                </div>
              </div>
              <div className="space-y-2">
                <p className="text-gray-300 text-sm font-semibold">Full Coverage</p>
                <div className="flex items-center gap-2">
                  <div className="flex-1 h-2 bg-gray-700 rounded-full overflow-hidden">
                    <div className="h-full bg-gradient-to-r from-blue-500 to-cyan-400 rounded-full" style={{ width: '100%' }}></div>
                  </div>
                  <span className="text-xs text-gray-500">100%</span>
                </div>
              </div>
            </div>

            {/* KPIs Tracked */}
            <div className="bg-gradient-to-br from-purple-500/10 via-pink-500/5 to-purple-500/10 border-2 border-purple-500/30 rounded-xl p-6 hover:border-purple-500/60 transition-all duration-300 backdrop-blur-sm group">
              <div className="flex items-start justify-between mb-4">
                <div className="p-3 bg-purple-500/20 rounded-xl group-hover:scale-110 transition-transform duration-300">
                  <BarChart3 className="text-purple-400" size={28} />
                </div>
                <div className="text-right">
                  <p className="text-5xl font-bold text-white mb-1">{executiveSummary?.totalKPIs || 0}</p>
                  <p className="text-xs text-purple-400 font-semibold uppercase tracking-wide">KPIs</p>
                </div>
              </div>
              <div className="space-y-2">
                <p className="text-gray-300 text-sm font-semibold">Real-Time Monitoring</p>
                <div className="flex items-center gap-1 text-xs text-gray-500">
                  <Activity size={12} className="text-purple-400 animate-pulse" />
                  <span>Live data stream</span>
                </div>
              </div>
            </div>

            {/* Alerts Status */}
            <div className={`bg-gradient-to-br ${(executiveSummary?.criticalAlerts || 0) > 0 ? 'from-red-500/10 via-orange-500/5 to-red-500/10 border-red-500/30' : 'from-green-500/10 via-emerald-500/5 to-green-500/10 border-green-500/30'} border-2 rounded-xl p-6 hover:border-opacity-60 transition-all duration-300 backdrop-blur-sm group`}>
              <div className="flex items-start justify-between mb-4">
                <div className={`p-3 ${(executiveSummary?.criticalAlerts || 0) > 0 ? 'bg-red-500/20' : 'bg-green-500/20'} rounded-xl group-hover:scale-110 transition-transform duration-300`}>
                  {(executiveSummary?.criticalAlerts || 0) > 0 ? (
                    <AlertTriangle className="text-red-400" size={28} />
                  ) : (
                    <CheckCircle className="text-green-400" size={28} />
                  )}
                </div>
                <div className="text-right">
                  <p className="text-5xl font-bold text-white mb-1">{executiveSummary?.criticalAlerts || 0}</p>
                  <p className={`text-xs font-semibold uppercase tracking-wide ${(executiveSummary?.criticalAlerts || 0) > 0 ? 'text-red-400' : 'text-green-400'}`}>
                    {(executiveSummary?.criticalAlerts || 0) > 0 ? 'CRITICAL' : 'ALL CLEAR'}
                  </p>
                </div>
              </div>
              <div className="space-y-2">
                <p className="text-gray-300 text-sm font-semibold">
                  {(executiveSummary?.criticalAlerts || 0) > 0 ? 'Requires Attention' : 'Systems Normal'}
                </p>
                {(executiveSummary?.warningAlerts || 0) > 0 && (
                  <p className="text-xs text-yellow-400">+{executiveSummary?.warningAlerts} warnings</p>
                )}
              </div>
            </div>
          </div>
        </div>

        {/* AI-Powered Strategic Insights */}
        <div className="mb-8 animate-fade-in-up">
          <div className="flex items-center justify-between mb-6">
            <div className="flex items-center gap-3">
              <div className="p-2 bg-gradient-to-br from-purple-500/20 to-pink-500/20 rounded-xl border border-purple-500/30">
                <Brain className="text-purple-400" size={24} />
              </div>
              <div>
                <h2 className="text-2xl font-bold text-white">AI Strategic Insights</h2>
                <p className="text-sm text-gray-400">Intelligent recommendations for executive action</p>
              </div>
            </div>
            <button className="flex items-center gap-2 px-4 py-2 bg-purple-600/20 hover:bg-purple-600/30 border border-purple-500/50 rounded-lg text-purple-300 text-sm font-semibold transition-all duration-200">
              View All <ChevronRight size={16} />
            </button>
          </div>

          <div className="grid grid-cols-1 lg:grid-cols-3 gap-6">
            {aiInsights.map((insight, idx) => (
              <div key={idx} className="animate-slide-in-right" style={{ animationDelay: `${idx * 100}ms` }}>
                <InsightCard
                  type={insight.type}
                  title={insight.title}
                  description={insight.description}
                  priority={insight.priority}
                  impact={insight.impact}
                  actionLabel={insight.actionLabel}
                  onAction={() => console.log('Action clicked')}
                />
              </div>
            ))}
          </div>
        </div>

        {/* Premium Executive KPIs with Sparklines */}
        <div className="mb-8">
          <div className="flex items-center justify-between mb-6">
            <div className="flex items-center gap-3">
              <div className="p-2 bg-gradient-to-br from-blue-500/20 to-cyan-500/20 rounded-xl border border-blue-500/30">
                <TrendingUp className="text-blue-400" size={24} />
              </div>
              <div>
                <h2 className="text-2xl font-bold text-white">Key Performance Indicators</h2>
                <p className="text-sm text-gray-400">Critical metrics driving business success</p>
              </div>
            </div>
          </div>

          <div className="space-y-8">
            {topExecutiveKPIs.map((category, idx) => (
              <div key={idx} className="animate-fade-in-up" style={{ animationDelay: `${idx * 150}ms` }}>
                <h3 className="text-lg font-bold text-gray-300 mb-4 flex items-center gap-2">
                  <div className="h-1 w-8 bg-gradient-to-r from-purple-500 to-pink-500 rounded"></div>
                  {category?.category || 'Category'}
                </h3>
                <div className="grid grid-cols-1 md:grid-cols-2 xl:grid-cols-4 gap-6">
                  {(category?.kpis || []).map((kpi, kpiIdx) => {
                    const isPositive = kpi?.change?.startsWith('+');
                    const isNegative = kpi?.change?.startsWith('-');
                    const trend = isPositive ? 'up' : isNegative ? 'down' : 'stable';
                    const status = kpi?.status?.toLowerCase() === 'excellent' ? 'excellent' :
                                   kpi?.status?.toLowerCase() === 'good' ? 'good' :
                                   kpi?.status?.toLowerCase() === 'warning' ? 'warning' : 'critical';

                    return (
                      <ExecutiveKPICard
                        key={kpiIdx}
                        title={kpi?.name || 'N/A'}
                        value={kpi?.value || 'N/A'}
                        change={kpi?.change}
                        trend={trend as 'up' | 'down' | 'stable'}
                        status={status as 'excellent' | 'good' | 'warning' | 'critical'}
                        sparklineData={generateSparklineData()}
                        icon={
                          category?.category === 'Financial Performance' ? <DollarSign size={18} /> :
                          category?.category === 'Operational Efficiency' ? <Target size={18} /> :
                          <Users size={18} />
                        }
                      />
                    );
                  })}
                </div>
              </div>
            ))}
          </div>
        </div>

        {/* Department Overview Grid - Premium Design */}
        <div className="mb-8">
          <div className="flex items-center justify-between mb-6">
            <div className="flex items-center gap-3">
              <div className="p-2 bg-gradient-to-br from-orange-500/20 to-red-500/20 rounded-xl border border-orange-500/30">
                <Building2 className="text-orange-400" size={24} />
              </div>
              <div>
                <h2 className="text-2xl font-bold text-white">Department Performance</h2>
                <p className="text-sm text-gray-400">Cross-functional health at a glance</p>
              </div>
            </div>
          </div>

          <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 xl:grid-cols-5 gap-6">
            {departments.map((dept, idx) => (
              <Link
                key={dept?.id || Math.random()}
                to={dept?.url || '#'}
                className="group block animate-scale-in"
                style={{ animationDelay: `${idx * 50}ms` }}
              >
                <div className="relative bg-gradient-to-br from-gray-800/60 via-gray-900/60 to-gray-800/60 backdrop-blur-sm border-2 border-gray-700/50 rounded-2xl p-6 hover:border-transparent hover:shadow-2xl transition-all duration-300 overflow-hidden">
                  {/* Gradient overlay on hover */}
                  <div className={`absolute inset-0 bg-gradient-to-br ${getThemeColor(dept?.theme)} opacity-0 group-hover:opacity-10 transition-opacity duration-300`}></div>

                  {/* Content */}
                  <div className="relative z-10">
                    {/* Header with Icon and Health Score */}
                    <div className="flex items-start justify-between mb-4">
                      <div className={`p-3 bg-gradient-to-br ${getThemeColor(dept?.theme)} rounded-xl shadow-lg group-hover:scale-110 transition-transform duration-300`}>
                        <span className="text-2xl">{dept?.icon || '📊'}</span>
                      </div>
                      <div className="text-right">
                        <div className="relative inline-block">
                          <svg width="50" height="50" className="transform -rotate-90">
                            <circle
                              cx="25"
                              cy="25"
                              r="20"
                              fill="none"
                              stroke="#1f2937"
                              strokeWidth="4"
                            />
                            <circle
                              cx="25"
                              cy="25"
                              r="20"
                              fill="none"
                              stroke="url(#mini-gradient)"
                              strokeWidth="4"
                              strokeDasharray={`${(dept?.healthScore || 0) * 1.26} 126`}
                              strokeLinecap="round"
                              className="transition-all duration-1000"
                            />
                            <defs>
                              <linearGradient id="mini-gradient" x1="0%" y1="0%" x2="100%" y2="100%">
                                <stop offset="0%" stopColor={dept?.healthScore >= 80 ? '#10b981' : dept?.healthScore >= 65 ? '#3b82f6' : dept?.healthScore >= 50 ? '#f59e0b' : '#ef4444'} />
                                <stop offset="100%" stopColor={dept?.healthScore >= 80 ? '#059669' : dept?.healthScore >= 65 ? '#2563eb' : dept?.healthScore >= 50 ? '#d97706' : '#dc2626'} />
                              </linearGradient>
                            </defs>
                          </svg>
                          <div className="absolute inset-0 flex items-center justify-center">
                            <span className="text-lg font-bold text-white">{dept?.healthScore || 0}</span>
                          </div>
                        </div>
                      </div>
                    </div>

                    {/* Department Name */}
                    <h3 className="text-white font-bold text-lg mb-3 group-hover:text-transparent group-hover:bg-gradient-to-r group-hover:bg-clip-text group-hover:from-white group-hover:to-gray-300 transition-all">
                      {dept?.name || 'Department'}
                    </h3>

                    {/* Key Metrics - Cleaner Design */}
                    <div className="space-y-2 mb-4">
                      {(dept?.keyMetrics || []).slice(0, 2).map((metric, idx) => (
                        <div key={idx} className="flex items-center justify-between text-sm">
                          <span className="text-gray-400 text-xs">{metric?.name || 'N/A'}</span>
                          <span className="text-white font-semibold">{metric?.value || 'N/A'}</span>
                        </div>
                      ))}
                    </div>

                    {/* Action Button */}
                    <div className="flex items-center justify-between pt-3 border-t border-gray-700/50 group-hover:border-gray-600 transition-colors">
                      <span className="text-gray-400 text-sm font-medium group-hover:text-white transition-colors">View Dashboard</span>
                      <ArrowRight className="text-gray-400 group-hover:text-white group-hover:translate-x-1 transition-all" size={16} />
                    </div>
                  </div>
                </div>
              </Link>
            ))}
          </div>
        </div>

        {/* Premium Footer */}
        <div className="mt-16 pt-8 border-t border-gray-800">
          <div className="flex items-center justify-between">
            <div className="flex items-center gap-6 text-sm text-gray-500">
              <div className="flex items-center gap-2">
                <div className="w-2 h-2 bg-green-400 rounded-full animate-pulse"></div>
                <span>Live Data</span>
              </div>
              <span>•</span>
              <span>Last Updated: {new Date(data.generatedAt).toLocaleTimeString()}</span>
              <span>•</span>
              <span>{executiveSummary?.totalKPIs}+ Metrics Tracked</span>
            </div>
            <div className="text-sm text-gray-500">
              <span className="bg-gradient-to-r from-purple-400 to-pink-500 bg-clip-text text-transparent font-semibold">
                ElevareAI™ Executive Intelligence Platform
              </span>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
};

export default DashboardExecutive;
